apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: kwonarina/todo-hw2
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        env:
        - name: PGHOST
          value: postgres.default.svc.cluster.local
        - name: PGUSER
          value: postgres
        - name: PGDATABASE
          value: todos
