apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  labels:
    app: postgres
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
